#all plots produced with this config will end with this string
FILE_SUFFIX: 'AF10B_Vbb_scan'
#list of the chips
CHIPS: ["AF10P_W22_1.2V","AF10P_W22_1.2V","AF10P_W22_1.2V","AF10P_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue','red','green']
#list of the labels for the plots
LABELS: ["AF10P Vbb=1.2V","AF10P Vbb=0V","AF10P Vbb=2.4V"]
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131231221018134906_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131232221018143725_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131233221018150741_DUT_thr300.root"
              ]
            ]