#all plots produced with this config will end with this string
FILE_SUFFIX: 'AF25B_Vbb_scan'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF25B_W22_0V","AF25B_W22_1.2V","AF25B_W22_2.4V","AF25B_W22_3.6V","AF25B_W22_4.8V"]
#list of the color used for the plots
COLORS: ['black','blue','red','green','orange']
#list of the labels for the plots
LABELS: ["AF25B Vbb=0V","AF25B Vbb=1.2V","AF25B Vbb=2.4V","AF25B Vbb=3.6V","AF25B Vbb=4.8V"]
#list of the path with the root file
NSIGMANOISE: 3

FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_thr300.root"
              ]
            ]
NOISE_PATHS: [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105003221015113630_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105004221015115835_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105005221015122025_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105006221015124330_DUT_noise.root"
            ]
