#all plots produced with this config will end with this string
FILE_SUFFIX: 'TB'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions',' @PS June 2022, 10 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF25P_W22_1.2V","AF25P_W22_1.2V","AF15P_W22_1.2V","AF15P_W22_1.2V","AF15P_W22_1.2V","AF10P_W22_1.2V","AF10P_W22_1.2V","AF10P_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue','red','green','orange','pink','yellow','grey']
#list of the labels for the plots
LABELS: ["AF25P Vbb=1.2V","AF25P Vbb=1.2V PS June","AF15P Vbb=1.2V","AF15P Vbb=1.2V PS June","AF15P Vbb=1.2V PS August","AF10P Vbb=1.2V","AF10P Vbb=1.2V PS June","AF10P Vbb=1.2V PS August"]
#list of tracking resolutions
TRACKINGRESOLUTIONS: [
                        [2.08,2.08],
                        [ 3.22, 3.22],
                        [2.08,2.08],
                        [ 3.22, 3.22],
                        [2.85,2.85],
                        [2.08,2.08],
                        [ 3.22, 3.22],
                        [2.85,2.85]
                    ]
#SPS = 2.08,2.08
#PSJune = 3.22, 3.22  # 3.15
#PSAugust = 2.85,2.85  # 2.43
NSIGMANOISE: 0
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF25P_W22B7/analysis_253195220220622195234_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr300.root"
              ],
              [
                  #"/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF15P_W22B3/analysis_255161234220624161249_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF15P_W22B2/analysis_347092422220828092436_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSJune22/AF10P_W22B24/analysis_252191712220621191727_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/PSAugust22/B2/AF10P_W22B28/analysis_344201631220825201636_DUT_thr300.root"
              ]
            ]
NOISE_PATHS: [
            ]