#all plots produced with this config will end with this string
FILE_SUFFIX: 'irradiated'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions','@PS August 2022, 12 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF15P_W22B16_IR2.5_2.4V","AF15P_W22B16_IR2.5_2.4V","AF15P_W22_4.8V","AF15P_W22_0V","AF15P_W22_2.4V","AF15P_W22_3.6V","AF15P_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue','red','green','yellow','pink','orange']
#list of the labels for the plots
LABELS: ["AF15P_W22B16 Vbb=2.4V 98-110","AF15P_W22B16 Vbb=2.4V 100"]
#number of sigma after which the efficiency and resolution are plottend
NSIGMANOISE: 0

TRACKINGRESOLUTIONS: [
                        [2.08,2.08],
                        [2.08,2.08]
                    ]
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B16/analysis_415211939221014230457_DUT_100_thr300.root"
              ]
            ]
#list of the path with the root files with for the fake hit rate studies
NOISE_PATHS: [
]
