#all plots produced with this config will end with this string
FILE_SUFFIX: 'jian'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF15P_W22_1.2V","AF15P_W22_1.2V","AF15P_W22_1.2V","AF15P_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue','green','pink','orange','red']
#list of the labels for the plots
LABELS: ["AF15P Giacomo","AF15P Jian"]
#number of sigma after which the efficiency and resolution are plottend
NSIGMANOISE: 3

TRACKINGRESOLUTIONS: [
                        [2.08,2.08],
                        [2.08,2.08],
                        [2.08,2.08],
                        [2.08,2.08]
                    ]
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr150.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_thr300.root"
              ],
              [
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr80.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr90.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr100.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr110.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr120.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr150.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr200.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr250.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/jian/analysis_run413221453_221013042711_DUT_30um_thr300.root",
              ]
            ]
#list of the path with the root files with for the fake hit rate studies
NOISE_PATHS: [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_noise.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_noise.root"
            ]
