#all plots produced with this config will end with this string
FILE_SUFFIX: 'seed'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions',' @PS June 2022, 10 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF15P_W22_1.2V","AF25P_W22_1.2V","AF10P_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue','red','green','orange','pink','yellow','grey']
#list of the labels for the plots
LABELS: ["AF15P Vbb=1.2V seed","AF25P Vbb=1.2V seed","AF10P Vbb=1.2V seed",]
NSIGMANOISE: 0
TRACKINGRESOLUTIONS: [
  [0,0],
  [0,0],
  [0,0]
]
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr0.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr20.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr40.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr60.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr60.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15P_W22B2/analysis_413221453221013042711_DUT_seed_thr200.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr0.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr20.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr40.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr60.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25P_W22B7/analysis_416153058221015153104_DUT_seed_thr200.root"
              ],
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr0.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr20.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr40.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr60.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10P_W22B28/analysis_415000658221014000702_DUT_seed_thr200.root"
              ]
            ]
NOISE_PATHS: [
            ]