#all plots produced with this config will end with this string
FILE_SUFFIX: 'test15b'
#status of the measurement
STATUS: 'WORK IN PROGRESS'
#test beam period and beam
TEST_BEAMS: ['@SPS October 2022, 120 GeV/c protons and pions']
#list of the chips
CHIPS: ["AF15B_W22_1.2V","AF15B_W22_1.2V"]
#list of the color used for the plots
COLORS: ['black','blue']
#list of the labels for the plots
LABELS: ["AF15B Vbb=1.2V Giacomo","AF15B Vbb=1.2V Riccardo"]
#number of sigma after which the efficiency and resolution are plottend
NSIGMANOISE: 3
#list of the path with the root file
FILE_PATHS: [
              [
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr80.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr100.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr120.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr140.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr160.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr200.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr250.root",
                  "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_thr300.root"
              ],
              [
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_80.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_100.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_120.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_140.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_160.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_200.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_250.root",
                  "/home/giacomo/AF15B_W22B4/analysis_run417165943_221016165948.raw_SPS_300.root"
              ]
              
            ]
#list of the path with the root files with for the fake hit rate studies
#list of the path with the root files with for the fake hit rate studies
NOISE_PATHS: [
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF10B_W22B15/analysis_422131230221018131235_DUT_noise.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF15B_W22B4/analysis_417165943221016165948_DUT_noise.root",
                "/home/giacomo/its-corryvreckan-tools/output/SPSOctober22/B1/AF25B_W22B8/analysis_416105001221015105005_DUT_noise.root"
            ]